#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
IMAGE_REPO=${IMAGE_NAME%:*}
IMAGE_TAG=${IMAGE_NAME#*:}

AIRFLOW_VERSION=${IMAGE_TAG%-*}
PYTHON_TAG=${IMAGE_TAG#*-}
PYTHON_VERSION=${PYTHON_TAG:6}

if [ $PYTHON_VERSION = "3" ]; then
    AIRFLOW_EXTRAS=async,celery,crypto,jdbc,hdfs,hive,azure,emr,password,postgres,slack,ssh
else
	AIRFLOW_EXTRAS=async,celery,crypto,jdbc,hdfs,hive,azure,gcp_api,emr,password,postgres,slack,ssh
fi

# Trigger build
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg PYTHON_VERSION=$PYTHON_VERSION \
             --build-arg AIRFLOW_VERSION=$AIRFLOW_VERSION \
             --build-arg AIRFLOW_EXTRAS=$AIRFLOW_EXTRAS \
             -t $IMAGE_NAME .