#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
IMAGE_REPO=${IMAGE_NAME%:*}
IMAGE_TAG=${IMAGE_NAME#*:}
VERSION_TAG=${IMAGE_TAG%-*}
PYTHON_TAG=${IMAGE_TAG#*-}

# Retag to latest
if [ "$IMAGE_TAG" = "1.10.1-python3.6" ]; then
    docker tag $IMAGE_NAME ${IMAGE_REPO}:latest
    docker push ${IMAGE_REPO}:latest
fi

if [ "$PYTHON_TAG" = "python3.6" ]; then
    docker tag $IMAGE_NAME ${IMAGE_REPO}:${VERSION_TAG}-python3
    docker push ${IMAGE_REPO}:${VERSION_TAG}-python3
fi